name: henson_field_app
description: Henson Field Service - Starter
publish_to: 'none'
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^0.3.0
  flutter_riverpod: ^2.0.0
  go_router: ^7.0.0
  uuid: ^3.0.6
  connectivity_plus: ^3.0.3
  image_picker: ^0.8.5+3
  signature: ^4.0.0
  flutter_map: ^4.0.0
  url_launcher: ^6.1.7
flutter:
  uses-material-design: true
